    const products = [
        //Guest Amenities
        { id: 1, name: "Dental Kit", price:100 , spec: "Colgate/anchor & white toothbrush packed in box", category: "Guest Amenities", image: "images/dental-kit.jpg" },
        { id: 2, name: "Shaving Kit", price:100 , spec: "Shaving Gel & /Razor Packed in Box", category: "Guest Amenities", image: "images/shaving-kit.jpg" },
        { id: 3, name: "Dental Kit", price:100 , spec: "Biotique", category: "Guest Amenities", image: "images/dental-kit-biotique.jpg" },
        { id: 4, name: "Shaving Kit", price:100 , spec: "Biotique", category: "Guest Amenities", image: "images/shaving-kit-biotique.jpg" },
        { id: 5, name: "Comb", price:100 , spec: "Handel Packed in Cover", category: "Guest Amenities", image: "images/comb.jpg" },
        { id: 6, name: "Shower Cap", price:100 , spec: "Packed In Box", category: "Guest Amenities", image: "images/shower-cap.jpg" },
        { id: 7, name: "Sewing Kit", price:100 , spec: "Packed in Box", category: "Guest Amenities", image: "images/sewing-kit.jpg" },
        { id: 8, name: "Shampoo", price:100 , spec: "15 ML", category: "Guest Amenities", image: "images/shampoo-15ml.jpg" },
        { id: 9, name: "Shower Gel", price:100 , spec: "15 ML", category: "Guest Amenities", image: "images/shower-gel-15ml.jpg" },
        { id: 10, name: "Moisturiser", price:100 , spec: "15 ML", category: "Guest Amenities", image: "images/moisturiser-15ml.jpg" },
        { id: 11, name: "Shampoo", price:100 , spec: "20 ML", category: "Guest Amenities", image: "images/shampoo-20ml.jpg" },
        { id: 12, name: "Shower Gel", price:100 , spec: "20 ML", category: "Guest Amenities", image: "images/shower-gel-20ml.jpg" },
        { id: 13, name: "Moisturiser", price:100 , spec: "20 ML", category: "Guest Amenities", image: "images/moisturiser-20ml.jpg" },
        { id: 14, name: "Soap", price:100 , spec: "12 GM", category: "Guest Amenities", image: "images/soap-12gm.jpg" },
        { id: 15, name: "Soap", price:100 , spec: "15 GM", category: "Guest Amenities", image: "images/soap-15gm.jpg" },
        { id: 16, name: "Soap", price:100 , spec: "20 GM", category: "Guest Amenities", image: "images/soap-20gm.jpg" },
        { id: 17, name: "Shoe Shiner", price:100 , spec: "Standard", category: "Guest Amenities", image: "images/shoe-shiner.jpg" },
        { id: 18, name: "Shoe Shiner", price:100 , spec: "Paper Strip", category: "Guest Amenities", image: "images/shoe-shiner-paper-strip.jpg" },
        { id: 19, name: "Laundry Bag", price:100 , spec: "Fiber Bag", category: "Guest Amenities", image: "images/laundry-bag.jpg" },
        { id: 20, name: "Sleeper", price:100 , spec: "Terry", category: "Guest Amenities", image: "images/sleeper.jpg" },
        { id: 21, name: "Paper Coster", price:100 , spec: "Standard", category: "Guest Amenities", image: "images/paper-coster.jpg" },
        { id: 22, name: "Pencil", price:100 , spec: "Single Colour", category: "Guest Amenities", image: "images/pencil.jpg" },
        { id: 23, name: "W.C. Band", price:100 , spec: "1000 pcs pack", category: "Guest Amenities", image: "images/wc-band.jpg" },
        //Paper Product
        { id: 24, name: "Toilet Roll", price:100 , spec: "50 GM", category: "Paper Product", image: "images/toilet-roll-50gm.jpg" },
        { id: 25, name: "Toilet Roll", price:100 , spec: "80 GM", category: "Paper Product", image: "images/toilet-roll-80gm.jpg" },
        { id: 26, name: "Toilet Roll", price:100 , spec: "100 GM", category: "Paper Product", image: "images/toilet-roll-100gm.jpg" },
        { id: 27, name: "M Fold", price:100 , spec: "100 PCS Debn Clean", category: "Paper Product", image: "images/m-fold.jpg" },
        { id: 28, name: "Paper Napkin", price:100 , spec: "Claret 30*30", category: "Paper Product", image: "images/paper-napkin-claret-30x30.jpg" },
        { id: 29, name: "Paper Napkin", price:100 , spec: "Debn Clean 30*30", category: "Paper Product", image: "images/paper-napkin-debn-30x30.jpg" },
        { id: 30, name: "Paper Napkin", price:100 , spec: "Leaf 30*30", category: "Paper Product", image: "images/paper-napkin-leaf-30x30.jpg" },
        { id: 31, name: "Paper Napkin", price:100 , spec: "Majestic 30*30", category: "Paper Product", image: "images/paper-napkin-majestic-30x30.jpg" },
        { id: 32, name: "Paper Napkin", price:100 , spec: "40*40", category: "Paper Product", image: "images/paper-napkin-40x40.jpg" },
        { id: 33, name: "Paper Napkin", price:100 , spec: "40*40", category: "Paper Product", image: "images/paper-napkin-40x40.jpg" },
        { id: 34, name: "Restaurent Napkin", price:100 , spec: "22*22", category: "Paper Product", image: "images/restaurant-napkin-22x22.jpg" },
        //Cap & Gloves
        { id: 35, name: "UT Cap", price:100 , spec: "100 PCS", category: "Cap & Gloves", image: "images/ut-cap.jpg" },
        { id: 36, name: "Paper Chef Cap", price:100 , spec: "80 PCS", category: "Cap & Gloves", image: "images/paper-chef-cap.jpg" },
        { id: 37, name: "Nitrile Gloves", price:100 , spec: "Use & Throw", category: "Cap & Gloves", image: "images/nitrile-gloves.jpg" },
        { id: 38, name: "Gloves Orange", price:100 , spec: "Standard", category: "Cap & Gloves", image: "images/gloves-orange.jpg" },
        //General Supply
        { id: 39, name: "Cling Flim", price:100 , spec: "300 MTR.", category: "General Supply", image: "images/cling-film-300mtr.jpg" },
        { id: 40, name: "Cling Flim", price:100 , spec: "600 MTR.", category: "General Supply", image: "images/cling-film-600mtr.jpg" },
        { id: 41, name: "Silver Foil", price:100 , spec: "1 KG", category: "General Supply", image: "images/silver-foil-1kg.jpg" },
        { id: 42, name: "Silver Foil", price:100 , spec: "72 MTR.", category: "General Supply", image: "images/silver-foil-72mtr.jpg" },
        { id: 43, name: "Silver Foil", price:100 , spec: "72 NO.", category: "General Supply", image: "images/silver-foil-72no.jpg" },
        { id: 44, name: "Candel Light", price:100 , spec: "50 PCS", category: "General Supply", image: "images/candle-light-50pcs.jpg" },
        { id: 45, name: "Aroma Oil", price:100 , spec: "1 KG", category: "General Supply", image: "images/aroma-oil-1kg.jpg" },
        { id: 46, name: "Artificial Wax", price:100 , spec: "200 GM", category: "General Supply", image: "images/artificial-wax-200gm.jpg" },
        { id: 47, name: "Artificial Wax", price:100 , spec: "TIN", category: "General Supply", image: "images/artificial-wax-tin.jpg" },
       //ECO FOOD PACKING / DISPOSABLES
        { id: 48, name: "Straw Pipe", price:100 , spec: "50 PCS", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/straw-pipe-50pcs.jpg" },
        { id: 49, name: "Straw Pipe", price:100 , spec: "100 PCS", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/straw-pipe-100pcs.jpg" },
        { id: 50, name: "Tea Cup", price:100 , spec: "40 PCS", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/tea-cup-40pcs.jpg" },
        { id: 51, name: "Water Glass", price:100 , spec: "40 PCS", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/water-glass-40pcs.jpg" },
        { id: 52, name: "Plastic Container", price:100 , spec: "300 ML", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/plastic-container-300ml.jpg" },
        { id: 53, name: "Plastic Container", price:100 , spec: "500 ML", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/plastic-container-500ml.jpg" },
        { id: 54, name: "Plastic Container", price:100 , spec: "650 ML", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/plastic-container-650ml.jpg" },
        { id: 55, name: "Plastic Container", price:100 , spec: "750 ML", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/plastic-container-750ml.jpg" },
        { id: 56, name: "Plastic Container", price:100 , spec: "1000 ML", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/plastic-container-1000ml.jpg" },
        { id: 57, name: "Ripple Paper Cup", price:100 , spec: "250 ML", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/ripple-paper-cup-250ml.jpg" },
        { id: 58, name: "Eco Paper Cup", price:100 , spec: "", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/eco-paper-cup.jpg" },
        { id: 59, name: "Eco Paper Plate", price:100 , spec: "", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/eco-paper-plate.jpg" },
        { id: 60, name: "Wooden Spoon", price:100 , spec: "100 PCS", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/wooden-spoon-100pcs.jpg" },
        { id: 61, name: "Plastick Spoon", price:100 , spec: "100 PCS", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/plastic-spoon-100pcs.jpg" },
        { id: 62, name: "Wooden Fork", price:100 , spec: "100 PCS", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/wooden-fork-100pcs.jpg" },
        { id: 63, name: "Plastick Fork", price:100 , spec: "100 PCS", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/plastic-fork-100pcs.jpg" },
        { id: 64, name: "Wooden Ice Spoon", price:100 , spec: "100 PCS", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/wooden-ice-spoon-100pcs.jpg" },
        { id: 65, name: "Tea Straier", price:100 , spec: "100 PCS", category: "ECO FOOD PACKING / DISPOSABLES", image: "images/tea-strainer-100pcs.jpg" },
        //HOUSEKEEPING PRODUCT
        { id: 66, name: "Broom Stick", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/broom-stick.jpg" },
        { id: 67, name: "Soft Broom", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/soft-broom.jpg" },
        { id: 68, name: "Sweeper Broom", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/sweeper-broom.jpg" },
        { id: 69, name: "Wet Mop Set", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/wet-mop-set.jpg" },
        { id: 70, name: "Wet Mop Refil", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/wet-mop-refil.jpg" },
        { id: 71, name: "Dry Mop Set", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/dry-mop-set.jpg" },
        { id: 72, name: "Dry Mop Refil", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/dry-mop-refil.jpg" },
        { id: 73, name: "Dustpan", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/dustpan.jpg" },
        { id: 74, name: "Dustpan", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/dustpan.jpg" },
        { id: 75, name: "Wiper Big", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/wiper-big.jpg" },
        { id: 76, name: "Wiper Medium", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/wiper-medium.jpg" },
        { id: 77, name: "Wiper Small", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/wiper-small.jpg" },
        { id: 78, name: "Kitchen Wiper", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/kitchen-wiper.jpg" },
        { id: 79, name: "Glass Wiper", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/glass-wiper.jpg" },
        { id: 80, name: "Glass Wiper", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/glass-wiper.jpg" },
        { id: 81, name: "Glass Wiper Squeege", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/glass-wiper-squeege.jpg" },
        { id: 82, name: "Green Pad Scrubber", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/green-pad-scrubber.jpg" },
        { id: 83, name: "Green Pad", price:100 , spec: "SCOTCH BRITE", category: "HOUSEKEEPING PRODUCT", image: "images/green-pad-scotch-brite.jpg" },
        { id: 84, name: "White Pad Scruber", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/white-pad-scrubber.jpg" },
        { id: 85, name: "Buffing Pad White", price:100 , spec: "3M", category: "HOUSEKEEPING PRODUCT", image: "images/buffing-pad-white.jpg" },
        { id: 86, name: "Buffing Pad Red", price:100 , spec: "3M", category: "HOUSEKEEPING PRODUCT", image: "images/buffing-pad-red.jpg" },
        { id: 87, name: "Buffing Pad Green", price:100 , spec: "3M", category: "HOUSEKEEPING PRODUCT", image: "images/buffing-pad-green.jpg" },
        { id: 88, name: "Buffing Pad Black", price:100 , spec: "3M", category: "HOUSEKEEPING PRODUCT", image: "images/buffing-pad-black.jpg" },
        { id: 89, name: "Sponge Wipes", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/sponge-wipes.jpg" },
        { id: 90, name: "Feather Brush", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/feather-brush.jpg" },
        { id: 91, name: "Carpet Brush", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/carpet-brush.jpg" },
        { id: 92, name: "W.C. Brush", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/wc-brush.jpg" },
        { id: 93, name: "Jobby Dust Pan", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/jobby-dust-pan.jpg" },
        { id: 94, name: "Apron Ut", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/apron-ut.jpg" },
        { id: 95, name: "Micro Fiber Duster", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/micro-fiber-duster.jpg" },
        { id: 96, name: "Micro Fiber Duster", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/micro-fiber-duster.jpg" },
        { id: 97, name: "Kitchen Duster", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/kitchen-duster.jpg" },
        { id: 98, name: "Floor Duster", price:100 , spec: "Small", category: "HOUSEKEEPING PRODUCT", image: "images/floor-duster-small.jpg" },
        { id: 99, name: "Floor Duster", price:100 , spec: "Medium", category: "HOUSEKEEPING PRODUCT", image: "images/floor-duster-medium.jpg" },
        { id: 100, name: "Floor Duster", price:100 , spec: "Big", category: "HOUSEKEEPING PRODUCT", image: "images/floor-duster-big.jpg" },
        { id: 101, name: "Odonil", price:100 , spec: "Odonil", category: "HOUSEKEEPING PRODUCT", image: "images/odonil.jpg" },
        { id: 102, name: "Air Freshner Refil", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/air-freshner-refil.jpg" },
        { id: 103, name: "Castic Soda", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/castic-soda.jpg" },
        { id: 104, name: "Urinal Cube", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/urinal-cube.jpg" },
        { id: 105, name: "Urinal Screen", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/urinal-screen.jpg" },
        { id: 106, name: "Naphthelene Balls", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/naphthelene-balls.jpg" },
        { id: 107, name: "Pitambari", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/pitambari.jpg" },
        { id: 108, name: "Spray Bottle", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/spray-bottle.jpg" },
        { id: 109, name: "Plastic Bucket", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/plastic-bucket.jpg" },
        { id: 110, name: "Plastic Mug", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/plastic-mug.jpg" },
        { id: 111, name: "Carry Bag", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/carry-bag.jpg" },
        { id: 112, name: "Packing Material", price:100 , spec: "Standerd", category: "HOUSEKEEPING PRODUCT", image: "images/packing-material.jpg" },
        { id: 113, name: "Garbage", price:100 , spec: "19*21", category: "HOUSEKEEPING PRODUCT", image: "images/garbage-19x21.jpg" },
        { id: 114, name: "Garbage", price:100 , spec: "40*42", category: "HOUSEKEEPING PRODUCT", image: "images/garbage-40x42.jpg" },
        { id: 115, name: "Garbage", price:100 , spec: "25*30", category: "HOUSEKEEPING PRODUCT", image: "images/garbage-25x30.jpg" },
        { id: 116, name: "Garbage", price:100 , spec: "30*37", category: "HOUSEKEEPING PRODUCT", image: "images/garbage-30x37.jpg" },
        { id: 117, name: "Garbage", price:100 , spec: "36*48", category: "HOUSEKEEPING PRODUCT", image: "images/garbage-36x48.jpg" },

        // Chemical
        { id: 118, name: "Taski R1", price:100 , spec: "TASKI", category: "Chemical", image: "images/taski-r1.jpg" },
        { id: 119, name: "Taski R2", price:100 , spec: "TASKI", category: "Chemical", image: "images/taski-r2.jpg" },
        { id: 120, name: "Taski R3", price:100 , spec: "TASKI", category: "Chemical", image: "images/taski-r3.jpg" },
        { id: 121, name: "Taski R4", price:100 , spec: "TASKI", category: "Chemical", image: "images/taski-r4.jpg" },
        { id: 122, name: "Taski R5", price:100 , spec: "TASKI", category: "Chemical", image: "images/taski-r5.jpg" },
        { id: 123, name: "Taski R6", price:100 , spec: "TASKI", category: "Chemical", image: "images/taski-r6.jpg" },
        { id: 124, name: "Taski R7", price:100 , spec: "TASKI", category: "Chemical", image: "images/taski-r7.jpg" },
        { id: 125, name: "Taski R9", price:100 , spec: "TASKI", category: "Chemical", image: "images/taski-r9.jpg" },
        { id: 126, name: "Suma Gril D9", price:100 , spec: "TASKI", category: "Chemical", image: "images/suma-gril-d9.jpg" },
        { id: 127, name: "Suma D5", price:100 , spec: "TASKI", category: "Chemical", image: "images/suma-d5.jpg" },
        { id: 128, name: "Taski Hand Wash 5 Ltr", price:100 , spec: "TASKI", category: "Chemical", image: "images/taski-hand-wash-5ltr.jpg" },
        { id: 129, name: "Suma Multi", price:100 , spec: "TASKI", category: "Chemical", image: "images/suma-multi.jpg" },
        { id: 130, name: "Taski D7", price:100 , spec: "TASKI", category: "Chemical", image: "images/taski-d7.jpg" },
        { id: 131, name: "TR101", price:100 , spec: "TASKI", category: "Chemical", image: "images/tr101.jpg" },
        { id: 132, name: "TR103", price:100 , spec: "TASKI", category: "Chemical", image: "images/tr103.jpg" },
        { id: 133, name: "Teronova (D9)", price:100 , spec: "TASKI", category: "Chemical", image: "images/teronova-d9.jpg" },
        { id: 134, name: "Suma Date", price:100 , spec: "TASKI", category: "Chemical", image: "images/suma-date.jpg" },
        { id: 135, name: "Noable", price:100 , spec: "TASKI", category: "Chemical", image: "images/noable.jpg" },
        { id: 136, name: "Liquid Soap Can", price:100 , spec: "Standard", category: "Chemical", image: "images/liquid-soap-can.jpg" },
        { id: 137, name: "Liquid Soap", price:100 , spec: "Standard", category: "Chemical", image: "images/liquid-soap.jpg" },
        { id: 138, name: "TCC 90", price:100 , spec: "Standard", category: "Chemical", image: "images/tcc-90.jpg" },
        { id: 139, name: "HCL Acid", price:100 , spec: "Standard", category: "Chemical", image: "images/hcl-acid.jpg" },
        { id: 140, name: "Sulfuric Acid", price:100 , spec: "Standard", category: "Chemical", image: "images/sulfuric-acid.jpg" },
        { id: 141, name: "Tile Cleaner (B1)", price:100 , spec: "BUZIL", category: "Chemical", image: "images/tile-cleaner-b1.jpg" },
        { id: 142, name: "Floor Cleaner (B2)", price:100 , spec: "BUZIL", category: "Chemical", image: "images/floor-cleaner-b2.jpg" },
        { id: 143, name: "Floor Cleaner (B2)", price:100 , spec: "BUZIL", category: "Chemical", image: "images/floor-cleaner-b2-alt.jpg" },
        { id: 144, name: "Glass Cleaner (B3)", price:100 , spec: "BUZIL", category: "Chemical", image: "images/glass-cleaner-b3.jpg" },
        { id: 145, name: "Furniture Polish (B4)", price:100 , spec: "BUZIL", category: "Chemical", image: "images/furniture-polish-b4.jpg" },
        { id: 146, name: "Room Spray (B5)", price:100 , spec: "BUZIL", category: "Chemical", image: "images/room-spray-b5.jpg" },
        { id: 147, name: "Room Spray (B5)", price:100 , spec: "BUZIL", category: "Chemical", image: "images/room-spray-b5-alt.jpg" },
        { id: 148, name: "Room Spray", price:100 , spec: "BUZIL/PRO", category: "Chemical", image: "images/room-spray.jpg" },
        { id: 149, name: "Room Spray", price:100 , spec: "Stan Fresh", category: "Chemical", image: "images/room-spray-stan-fresh.jpg" },
        { id: 150, name: "Toilet Cleaner", price:100 , spec: "PRO/BUZIL", category: "Chemical", image: "images/toilet-cleaner.jpg" },
        { id: 151, name: "Toilet Cleaner", price:100 , spec: "BUZIL", category: "Chemical", image: "images/toilet-cleaner-buzil.jpg" },
        { id: 152, name: "Toilet Cleaner", price:100 , spec: "BUZIL", category: "Chemical", image: "images/toilet-cleaner-buzil-alt.jpg" },
        { id: 153, name: "Meta Pol (Steel Polish)", price:100 , spec: "Standard", category: "Chemical", image: "images/meta-pol-steel-polish.jpg" },
        { id: 154, name: "Bathroom Cleaner (B9)", price:100 , spec: "BUZIL", category: "Chemical", image: "images/bathroom-cleaner-b9.jpg" },
        { id: 155, name: "Floor Cleaner", price:100 , spec: "BUZIL", category: "Chemical", image: "images/floor-cleaner.jpg" },
        { id: 156, name: "Glass Cleaner (B3)", price:100 , spec: "Stan Fresh", category: "Chemical", image: "images/glass-cleaner-b3-stan-fresh.jpg" },
        { id: 157, name: "Dish Wash", price:100 , spec: "Stan Fresh", category: "Chemical", image: "images/dish-wash.jpg" },
        { id: 158, name: "Hand Wash", price:100 , spec: "PRO/BUZIL", category: "Chemical", image: "images/hand-wash.jpg" },
        { id: 159, name: "Hand Wash", price:100 , spec: "BUZIL", category: "Chemical", image: "images/hand-wash-buzil.jpg" },
        { id: 160, name: "Sodium Hypo Cloride", price:100 , spec: "Standard", category: "Chemical", image: "images/sodium-hypo-cloride.jpg" },
        { id: 161, name: "Alife Lemon Hand Wash", price:100 , spec: "Fortune (Adani Wilmar)", category: "Chemical", image: "images/alife-lemon-hand-wash.jpg" },
        { id: 162, name: "Alife Floral Hand Wash", price:100 , spec: "Fortune (Adani Wilmar)", category: "Chemical", image: "images/alife-floral-hand-wash.jpg" },
        { id: 163, name: "Ozel Multipurpose Cleaner", price:100 , spec: "Fortune (Adani Wilmar)", category: "Chemical", image: "images/ozel-multipurpose-cleaner.jpg" },
    ];
